spring:
  # Mysql ˝æ›ø‚≈‰÷√
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true

  # RabbitMQ≈‰÷√
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

  # Redis≈‰÷√
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 1024
        max-wait: -1s
        max-idle: 200
  jpa:
    hibernate:
      ddl-auto: create-drop

